author: "Rayan Islam"
email: "rayan.islam.2586@gmail.com"
baseurl: "" # Leave empty if hosted at <username>.github.io
url: "https://rayan-islam.github.io" # Replace with your URL

# Theme Settings
remote_theme: pages-themes/hacker@v0.2.0

# Metadata for SEO
keywords: "Portfolio, GitHub, Hacker Theme, Projects, Skills"

# Navigation Links
nav_links:
  - name: "Home"
    url: "/"
  - name: "Projects"
    url: "/projects/"
  - name: "Skills"
    url: "/skills/"
  - name: "Research"
    url: "/research/"
  - name: "Contact"
    url: "/contact/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one
